services:
  responsiveviewer:
    image: responsiveviewer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 32000:3000
      - 9229:9229
    command: ['node', '--inspect=0.0.0.0:9229', './scripts/start.js']
